export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS'
export const ADD_QUESTION = 'ADD_QUESTION'
export const ADD_QUESTION_ANSWER = 'ADD_QUESTION_ANSWER'

export const SET_LOGGED_USER = 'SET_LOGGED_USER'
export const ADD_ANSWER_TO_LOGGED_USER = 'ADD_ANSWER_TO_LOGGED_USER'

export const RECEIVE_USERS = 'RECEIVE_USERS'
export const ADD_ANSWER = 'ADD_ANSWER'
export const ADD_QUESTION_TO_USER_QUESTIONS = 'ADD_QUESTION_TO_USER_QUESTIONS'
